CREATE TABLE IF NOT EXISTS csv_batch (
    id VARCHAR(64) PRIMARY KEY,
    source TEXT NOT NULL,
    items JSON NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    results JSON NOT NULL,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
