from __future__ import annotations
from typing import Protocol, TypeVar
from uuid import UUID
from pydantic import BaseModel
from kedb.domain import JiraIssue, KnownError, ArticleVersion, HumanReview, RetrievalCandidate, ArticleChunk

T = TypeVar('T', bound=BaseModel)

class KnownErrorRepository(Protocol):
    def get(self, id: UUID) -> KnownError | None: ...
    def add(self, entity: KnownError) -> None: ...
    def list(self) -> list[KnownError]: ...

class ArticleVersionRepository(Protocol):
    def list_for_known_error(self, known_error_id: UUID) -> list[ArticleVersion]: ...
    def get(self, id: UUID) -> ArticleVersion | None: ...
    def add(self, entity: ArticleVersion) -> None: ...

class JiraIssueRepository(Protocol):
    def get(self, id: UUID) -> JiraIssue | None: ...
    def add(self, entity: JiraIssue) -> None: ...

class ReviewRepository(Protocol):
    def add(self, entity: HumanReview) -> None: ...
    def latest_for_workflow(self, workflow_id: UUID) -> HumanReview | None: ...

class SearchPort(Protocol):
    def search(self, query: str, exact_identifiers: list[str], top_k: int = 5) -> list[RetrievalCandidate]: ...

class LLMProvider(Protocol):
    def structured(self, *, system: str, user: str, schema: type[T]) -> T: ...

class Publisher(Protocol):
    def publish_chunks(self, article: ArticleVersion, chunks: list[ArticleChunk]) -> None: ...
