from __future__ import annotations
from typing import Protocol
from uuid import UUID
from kedb.domain.entities import ArticleChunk, ArticleVersion, JiraIssue, KnownError, RetrievalCandidate, HumanReview


class KnowledgeRepository(Protocol):
    def save_issue(self, issue: JiraIssue) -> JiraIssue: ...
    def get_issue(self, issue_id: UUID) -> JiraIssue | None: ...
    def create_known_error(self, item: KnownError) -> KnownError: ...
    def get_known_error(self, known_error_id: UUID) -> KnownError | None: ...
    def next_version_number(self, known_error_id: UUID) -> int: ...
    def save_version(self, version: ArticleVersion) -> ArticleVersion: ...
    def get_version(self, version_id: UUID) -> ArticleVersion | None: ...
    def save_chunks(self, chunks: list[ArticleChunk]) -> None: ...
    def list_published_versions(self) -> list[ArticleVersion]: ...
    def link_issue(self, issue_id: UUID, known_error_id: UUID, confidence: float) -> None: ...
    def set_current_version(self, known_error_id: UUID, version_id: UUID) -> None: ...
    def save_review(self, review: HumanReview) -> HumanReview: ...


class ExactSearchPort(Protocol):
    def search(self, issue: JiraIssue, limit: int = 10) -> list[RetrievalCandidate]: ...


class LexicalSearchPort(Protocol):
    def search(self, query: str, limit: int = 10) -> list[RetrievalCandidate]: ...


class VectorStorePort(Protocol):
    def upsert(self, chunks: list[ArticleChunk], vectors: list[list[float]], metadata: list[dict]) -> None: ...
    def search(self, vector: list[float], limit: int = 10) -> list[RetrievalCandidate]: ...


class EmbeddingPort(Protocol):
    def embed(self, text: str) -> list[float]: ...
    def embed_batch(self, texts: list[str]) -> list[list[float]]: ...


class LLMPort(Protocol):
    def structured(self, system_prompt: str, user_prompt: str, schema: type): ...
